apiVersion: v1
kind: Service
metadata:
  name: spark-master
  labels:
    app: spark
    component: master
spec:
  ports:
    - port: 7077
      name: spark
    - port: 8080
      name: webui
  selector:
    app: spark
    component: master
  #type: LoadBalancer
  clusterIP: None

