apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
  labels:
    app: spark
    component: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark
      component: worker
  template:
    metadata:
      labels:
        app: spark
        component: worker
    spec:
      containers:
        - name: spark-worker
          image: quay.io/sswguo/spark-worker:3.4.0-jdk11-1.5
          env:
            - name: SPARK_MASTER_URL
              value: "spark://spark-master:7077"
          ports:
            - containerPort: 8081
          resources:
            limits:
              cpu: 2
              memory: 2000Mi
            requests:
              cpu: 300m
              memory: 400Mi
          volumeMounts:
            - name: vol-migration-data
              mountPath: /opt/spark/storage
      volumes:
        - name: vol-migration-data
          persistentVolumeClaim:
            claimName: vol-migration-data


