apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
  labels:
    app: spark
    component: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spark
      component: worker
  template:
    metadata:
      labels:
        app: spark
        component: worker
    spec:
      containers:
        - name: spark-worker
          image: quay.io/sswguo/spark-worker:3.4.0-jdk11-1.5
          env:
            - name: SPARK_MASTER_URL
              value: "spark://spark-master:7077"
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: vol-migration-data
              mountPath: /opt/spark/storage
      volumes:
        - name: vol-migration-data
          persistentVolumeClaim:
            claimName: vol-migration-data
  volumeClaimTemplates:
    - metadata:
        name: "vol-migration-data"
      spec:
        accessModes: [ "ReadWriteMany" ]
        resources:
          requests:
            storage: "20Gi"
        storageClassName: "dynamic-nfs"


