kind: Deployment
apiVersion: apps/v1
metadata:
  name: aws-cli
  namespace: indy-preview
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-cli
  template:
    metadata:
      labels:
        app: aws-cli
    spec:
      volumes:
        - name: vol-migration-data
          persistentVolumeClaim:
            claimName: vol-migration-data
      containers:
        - resources:
            limits:
              cpu: '2'
              memory: 4Gi
            requests:
              cpu: '1'
              memory: 4Gi
          terminationMessagePath: /dev/termination-log
          name: aws-cli
          env:
            - name: AWS_DEFAULT_REGION
              value: us-east-1
            - name: AWS_REGION
              value: us-east-1
          imagePullPolicy: Always
          volumeMounts:
            - name: vol-migration-data
              mountPath: /opt/spark/storage
          terminationMessagePolicy: File
          image: 'quay.io/ligangty/nos-aws-cli:latest'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
